title: BSides Asbury
email: info@bsidesnj.net
description: Landing page for BSides Asbury Information Security Conference
author: BSidesNJ

# Social Profiles
twitter_username:
github_username:
facebook_username:
